name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  http: ^0.13.5
  html: ^0.15.2
  hive: ^2.2.3
  flutter_riverpod: ^2.3.5
  adaptive_theme: ^3.2.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  hydrated_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  